name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.6
  equatable: ^2.0.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
