name: theme_repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
