name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
